import numpy as np
print("1Dimensional array")
a=np.array([1,2,3])
print(a)
print("------------------")
print("2Dimensional array")
a1=np.array([[1,2],[3,4]])
print("ndim --> no of dimension :")
print(a1.ndim)
print("------------------")
print("shape --> to tell the shape of the matrix rows and column :")
print(a1.shape)
print("------------------")
print("size --> tells the no of elements in the array :")
print(a1.size)
print("------------------")
print("insert --> helps us to insert the elements at any place & doe not modify the original array (1Dimensional :) ")
b=np.insert(a,1,4)
print(b)
print("------------------")
print("insert --> helps us to insert the elements at any place & doe not modify the original array (multiple elements :) ")
b1=np.insert(a,[2,3],[5,6])
print(b1)
print("------------------")
print("insert --> helps us to insert the elements at any place & doe not modify the original array (2Dimensional :) ")
b2=np.insert(a1,1,[5,6])
print(b2)
print("------------------")
print("append --> helps to add the element at end of the array : ")
print(np.append(a,5))
print("------------------")
print("arange --> helps to genrate the random numbers in the given range from start to stop-1 , if needed add the step")
b3=np.arange(1,101,2)
print(b3)
print("------------------")